### ISSUE TITLE
sozuctl query applications doesn't return a result

### ISSUE THREAD

**Issue by BlackYoup** [sozu-proxy/sozu#708] opened 2021-09-15 09:27 UTC
I'm currently trying to query an application using `sozuctl -c /etc/sozu/config.toml query applications -i <id>` or `sozuctl -c /etc/sozu/config.toml query applications -d <domain>` but none of those commands ever return.

No weird CPU consumption happens. Sozu version tested: 0.13.6

**Comment by Keksoj** [comment] 2021-09-16 13:35
I don't manage to reproduce the bug, locally everything works fine. The issue may occur only when there are thousands of applications present.

**Comment by Keksoj** [comment] 2021-09-22 14:01
Well at least we should have a timeout, so there's that.

**Comment by Keksoj** [comment] 2021-11-09 17:22
The timeout is fixed in 

- #724

**Comment by Keksoj** [comment] 2021-11-15 15:03
The timeout is not fixed actually. Not that #724 doesn't matter, but this seems to be blocking:

```rust
                match self.sock.read(self.front_buf.space()) {
```

https://github.com/sozu-proxy/sozu/blob/d5a7da086f1bc27b60534f99b54b36ebd62c6805/command/src/channel.rs#L289

**Comment by Keksoj** [comment] 2022-03-09 13:30
It appears the command may just take VERY long to return in case of a huge state.

**Closed** 2022-10-12 12:30 UTC
Labels: bug
