### ISSUE TITLE
Panic in SendProxyProtocol::set_back_connected: frontend address should be available

### ISSUE THREAD

**Issue by BlackYoup** [sozu-proxy/sozu#505] opened 2018-07-26 22:22 UTC
I got this panic on current master a few hours ago:

```
(gdb) bt
#0  0x00007f9d940f2ef6 in strlen () from /usr/x86_64-pc-linux-gnu/lib/libc.so.6
#1  0x0000557a3a9e381d in std::sys::unix::backtrace::printing::resolve_symname ()
#2  0x0000557a3a9ee8ea in std::sys_common::backtrace::print ()
#3  0x0000557a3a9e13a6 in std::panicking::default_hook::{{closure}} ()
#4  0x0000557a3a9e10f9 in std::panicking::default_hook ()
#5  0x0000557a3a9e1812 in std::panicking::rust_panic_with_hook ()
#6  0x0000557a3a9e1606 in std::panicking::begin_panic_fmt ()
#7  0x0000557a3a9e1532 in rust_begin_unwind ()
#8  0x0000557a3aa3eeb3 in core::panicking::panic_fmt ()
#9  0x0000557a3a5d60d9 in core::result::unwrap_failed ()
#10 0x0000557a3a5d9d76 in <sozu_lib::network::protocol::proxy_protocol::send::SendProxyProtocol<Front>>::set_back_connected ()
#11 0x0000557a3a69ccd7 in <sozu_lib::network::tcp::Client as sozu_lib::network::ProxyClient>::ready ()
#12 0x0000557a3a6af536 in sozu_lib::network::proxy::Server::ready ()
#13 0x0000557a3a6a7b57 in sozu_lib::network::proxy::Server::run ()
#14 0x0000557a3a56a876 in sozu::worker::begin_worker_process ()
#15 0x0000557a3a4e7f15 in sozu::main ()
#16 0x0000557a3a4dd143 in std::rt::lang_start::{{closure}} ()
#17 0x0000557a3a9e14b3 in std::panicking::try::do_call ()
#18 0x0000557a3a9f51ca in __rust_maybe_catch_panic ()
#19 0x0000557a3a9dd606 in std::rt::lang_start_internal ()
#20 0x0000557a3a4ea1e4 in main ()
```

I only have one application that sends the proxy headers and it's a TCP application. I can't tell much how this is happening. Here are some logs. They may not be accurate, I have a lot of logs (~100 lines / second):
```
Jul 26 19:00:50 exherbo-dedicated sozu[21436]: 2018-07-26T17:00:50Z 17534858722357506 9292 WRK-25 TRACE sozu_lib::network::tcp  PROXY   9efddf19-24db-4046-b8f6-ca51a83a9a67    MyApp        Token(12) Readiness { front_interest: R-EH, front_readiness: -W--, back_i
Jul 26 19:00:50 exherbo-dedicated sozu[21436]: 2018-07-26T17:00:50Z 17534858722371106 9292 WRK-25 TRACE sozu_lib::network::protocol::pipe       pipe back_writable
Jul 26 19:00:50 exherbo-dedicated sozu[21436]: 2018-07-26T17:00:50Z 17534858722382026 9292 WRK-25 TRACE sozu_lib::network::tcp  PROXY   9efddf19-24db-4046-b8f6-ca51a83a9a67    MyApp        Token(12) Readiness { front_interest: R-EH, front_readiness: -W--, back_i
Jul 26 19:00:50 exherbo-dedicated sozu[21436]: 2018-07-26T17:00:50Z 17534858722395556 9292 WRK-25 TRACE sozu_lib::network::proxy        client[ClientToken(13) -> Token(13)] got events Writable and returned order Continue
Jul 26 19:00:50 exherbo-dedicated sozu[21436]: 2018-07-26T17:00:50Z 17534858722418325 9292 WRK-25 TRACE sozu_lib::network::proxy        PROXY   Token(13) got events: Readable | Writable | Error | Hup
Jul 26 19:00:50 exherbo-dedicated sozu[21436]: 2018-07-26T17:00:50Z 17534858722432695 9292 WRK-25 TRACE sozu_lib::network::tcp  token Token(13) got event RWEH
Jul 26 19:00:50 exherbo-dedicated sozu[21436]: 2018-07-26T17:00:50Z 17534858722446085 9292 WRK-25 TRACE sozu_lib::network::tcp  PROXY   9efddf19-24db-4046-b8f6-ca51a83a9a67    MyApp        Token(12) Readiness { front_interest: R-EH, front_readiness: -W--, back_i
Jul 26 19:00:50 exherbo-dedicated sozu[21436]: 2018-07-26T17:00:50Z 17534858722459885 9292 WRK-25 TRACE sozu_lib::network::protocol::pipe       pipe back_readable
Jul 26 19:00:50 exherbo-dedicated sozu[21436]: 2018-07-26T17:00:50Z 17534858722475585 9292 WRK-25 DEBUG sozu_lib::network::protocol::pipe       e634399c-03ab-4a1a-b789-83211265d8b6    unknown         BACK  [12<-13]: read 187 bytes
Jul 26 19:00:50 exherbo-dedicated sozu[21436]: 2018-07-26T17:00:50Z 17534858722500215 9292 WRK-25 INFO  9efddf19-24db-4046-b8f6-ca51a83a9a67    MyApp       188.76.16.84:17175 -> 127.0.0.1:45567   0 0 68 0
Jul 26 19:00:50 exherbo-dedicated sozu[21436]: 2018-07-26T17:00:50Z 17534858722513914 9292 WRK-25 ERROR PROXY client Token(12) back error, disconnecting
Jul 26 19:00:50 exherbo-dedicated sozu[21436]: 2018-07-26T17:00:50Z 17534858722524564 9292 WRK-25 TRACE sozu_lib::network::proxy        client[ClientToken(13) -> Token(13)] got events Readable | Writable | Error | Hup and returned order CloseClient
Jul 26 19:00:50 exherbo-dedicated sozu[21436]: 2018-07-26T17:00:50Z 17534858754920404 9292 WRK-25 TRACE sozu_lib::network::proxy        PROXY   Token(6) got events: Readable
Jul 26 19:00:50 exherbo-dedicated sozu[21436]: 2018-07-26T17:00:50Z 17534858755048123 9292 WRK-25 DEBUG sozu_lib::network::backends     Connecting MyApp -> (V4(127.0.0.1:45567), 0, 0)
Jul 26 19:00:50 exherbo-dedicated sozu[21436]: 2018-07-26T17:00:50Z 17534858755220151 9292 WRK-25 TRACE sozu_lib::network::proxy        PROXY   Token(12) got events: Writable
Jul 26 19:00:50 exherbo-dedicated sozu[21436]: 2018-07-26T17:00:50Z 17534858755261951 9292 WRK-25 TRACE sozu_lib::network::tcp  token Token(12) got event -W--
Jul 26 19:00:50 exherbo-dedicated sozu[21436]: 2018-07-26T17:00:50Z 17534858755279290 9292 WRK-25 TRACE sozu_lib::network::tcp  PROXY   8d4248d7-1860-4777-8227-6ae7db074e59    MyApp        Token(12) Readiness { front_interest: --EH, front_readiness: -W--, back_i
Jul 26 19:00:50 exherbo-dedicated sozu[21436]: 2018-07-26T17:00:50Z 17534858755295890 9292 WRK-25 TRACE sozu_lib::network::proxy        client[ClientToken(12) -> Token(12)] got events Writable and returned order Continue
Jul 26 19:00:50 exherbo-dedicated sozu[21436]: 2018-07-26T17:00:50Z 17534858755308890 9292 WRK-25 TRACE sozu_lib::network::proxy        PROXY   Token(13) got events: Writable
Jul 26 19:00:50 exherbo-dedicated sozu[21436]: 2018-07-26T17:00:50Z 17534858755321000 9292 WRK-25 TRACE sozu_lib::network::tcp  token Token(13) got event -W--
Jul 26 19:00:50 exherbo-dedicated sozu[21436]: thread 'main' panicked at 'frontend address should be available: Os { code: 107, kind: NotConnected, message: "Transport endpoint is not connected" }', libcore/result.rs:945:5
```

**Comment by Geal** [comment] 2018-07-27 09:31
duplicate of #450?

**Closed** 2020-01-10 10:38 UTC
